## **Questions based on Titanic Dataset:**

To read the dataset as csv, use the below code:

```python
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
```

### `Q-1:` Using `groupby` make groups using the `"Pclass"` column and find out the average age and total number of missing values in the `"Age"` column for every group.

In [58]:
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
titanic_df
titanic_df.groupby('Pclass')['Age'].agg(['mean',lambda x: x.isnull().sum()])

             mean  <lambda_0>
Pclass
1       38.233441          30
2       29.877630          11
3       25.140620         136

### `Q-2:` Using `groupby` make groups using the `"Pclass"` column and fill every group's `"Embarked"` column's missing values with the mode value of that group. After that, print every group's `"Embarked"` column's value counts in ascending order.

In [62]:
def fill_embarked_mode(group):
  mode_value=group['Embarked'].mode()[0]
  group['Embarked']=group['Embarked'].fillna(mode_value)
  return group

titanic_df=titanic_df.groupby('Pclass',group_keys=False).apply(fill_embarked_mode)

for pclass,group in titanic_df.groupby('Pclass'):
  print(pclass)
  print(group['Embarked'].value_counts().sort_values(ascending=True))

1
Embarked
Q      2
C     85
S    129
Name: count, dtype: int64
2
Embarked
Q      3
C     17
S    164
Name: count, dtype: int64
3
Embarked
C     66
Q     72
S    353
Name: count, dtype: int64

/tmp/ipykernel_1634/2945454027.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  titanic_df=titanic_df.groupby('Pclass',group_keys=False).apply(fill_embarked_mode)

### `Q-3:` Make groups based on `"Embarked"` column. And for each of this embarked group, make another group based on `"Pclass"` and find out the average fare (round off up to 2 decimal places) for each "Pclass" for each group of "Embarked".

**Sample Output:**

```bash
{'C': {1: 105, 2: 25, 3: 11},
 'Q': {1: 90, 2: 12, 3: 11},
 'S': {1: 70, 2: 20, 3: 15}}
```

In [72]:
titanic_df.groupby(['Embarked','Pclass'])['Fare'].mean().round(2).unstack().to_dict(orient='index')
# temp.groupby('Pclass').mean()

{'C': {1: 104.72, 2: 25.36, 3: 11.21},
 'Q': {1: 90.0, 2: 12.35, 3: 11.18},
 'S': {1: 70.51, 2: 20.33, 3: 14.64}}

## **Questions Based on Fifa Worldcup - 2022 Dataset:**

You can read the dataset by using the below sample code

```python
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
```

### `Q-4:` Perform `groupby` based on the `"Team"` column and then perform Z Normalization on top of the below columns of each group:
1. Passes
2. Passes Completed
3. Attempted Line Breaks
4. Completed Line Breaks

You have to make a python function named `z_normalization` which takes two arguments:

1. *group:* Every group that you have created
2. *cols_to_perform:* This parameter takes a list of columns on which you have to perform the Z-Normalization.

For this problem, you have to use th `apply()` method.

$\Large Z \ - \ Normalization = \frac{X_i - \mu}{std} $

After that find out the below values for each group:
- minimum "Passess"
- maximum "Passess"
- minimum "Yellow Cards"
- maximum "Yellow cards"
- average "Yellow Cards"
- maximum "Attempted Line Breaks"
- minimum "Attempted Line Breaks"
- standardard deviation of "Attempted Line Breaks"
- average Possession

In [99]:
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
fifa_df.head(2)

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,...,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,...,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,...,15,4,484,419,26,10,3,17,1,3

In [101]:
def z_normalization(group, cols_to_perform):
    u = group[cols_to_perform].mean()
    std = group[cols_to_perform].std()
    group[cols_to_perform] = (group[cols_to_perform] - u) / std
    return group


cols = ['Passes','Passes Completed','Attempted Line Breaks','Completed Line Breaks']

fifa_df = fifa_df.groupby('Team', group_keys=False).apply(z_normalization, cols)

result = fifa_df.groupby('Team').agg({
    'Passes': ['min', 'max'],
    'Yellow Cards': ['min', 'max', 'mean'],
    'Attempted Line Breaks': ['max', 'min', 'std'],
    'Possession (%)': ['mean']
})
result

/tmp/ipykernel_1634/899401547.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  fifa_df = fifa_df.groupby('Team', group_keys=False).apply(z_normalization, cols)

                  Passes           Yellow Cards                \
                     min       max          min max      mean
Team
Argentina      -1.510257  1.685214            0   8  2.285714
Australia      -1.114789  0.932782            0   3  1.750000
Belgium        -1.082696  0.888950            1   3  1.666667
Brazil         -0.928871  1.609122            0   3  1.200000
Cameroon       -0.875605  1.089713            1   5  2.666667
Canada         -1.120897  0.800641            2   4  2.666667
Costa Rica     -1.013178  0.986279            1   3  2.000000
Croatia        -1.441280  1.093005            0   2  1.142857
Denmark        -1.046208  0.946290            1   2  1.666667
Ecuador        -0.883020  1.085876            0   2  1.000000
England        -0.877731  1.705844            0   1  0.200000
France         -1.219077  1.571019            0   3  1.142857
Germany        -1.131449  0.765392            0   3  1.000000
Ghana          -1.045786  0.946861            2   4  2.666667
Iran           -0.820695  1.113800            2   3  2.333333
Japan          -1.001479  0.979825            0   3  1.500000
Korea Republic -1.157924  0.877868            1   2  1.500000
Mexico         -0.918398  1.065342            1   4  2.333333
Morocco        -1.384362  1.662218            0   3  1.285714
Netherlands    -1.051749  1.428668            0   4  1.800000
Poland         -0.694755  1.483035            1   3  1.750000
Portugal       -1.646177  1.035658            0   3  1.200000
Qatar          -1.147558  0.684833            0   4  2.333333
Saudi Arabia   -0.667896  1.149691            2   6  4.666667
Senegal        -1.214144  1.235077            1   3  1.750000
Serbia         -1.089807  0.875419            2   7  4.000000
Spain          -1.498758  0.554601            0   1  0.500000
Switzerland    -1.469082  0.754945            1   4  2.250000
Tunisia        -0.965692  1.031097            1   3  1.666667
United States  -1.136338  0.860862            0   4  1.250000
Uruguay        -0.931702  1.056570            1   3  2.000000
Wales          -0.971590  1.026174            1   2  1.666667

               Attempted Line Breaks                Possession (%)
                                 max       min  std           mean
Team
Argentina                   1.757406 -1.027917  1.0      49.285714
Australia                   0.961409 -1.187623  1.0      31.250000
Belgium                     1.109400 -0.832050  1.0      49.000000
Brazil                      1.085013 -1.627519  1.0      50.400000
Cameroon                    0.788942 -1.124661  1.0      38.333333
Canada                      0.865260 -1.094819  1.0      44.333333
Costa Rica                  0.590132 -1.154606  1.0      27.333333
Croatia                     1.187420 -1.785063  1.0      47.428571
Denmark                     1.000000 -1.000000  1.0      51.333333
Ecuador                     1.019020 -0.979827  1.0      42.666667
England                     1.354603 -1.172641  1.0      57.200000
France                      1.147789 -1.327966  1.0      44.857143
Germany                     1.036065 -0.959538  1.0      53.000000
Ghana                       0.979199 -1.019578  1.0      37.000000
Iran                        0.640642 -1.152297  1.0      31.666667
Japan                       1.377855 -0.948495  1.0      30.250000
Korea Republic              0.840338 -1.449814  1.0      42.250000
Mexico                      0.589590 -1.154613  1.0      46.666667
Morocco                     1.006855 -1.718366  1.0      34.285714
Netherlands                 1.128588 -1.222637  1.0      44.000000
Poland                      0.626272 -1.493418  1.0      32.000000
Portugal                    1.655185 -0.796941  1.0      53.800000
Qatar                       1.115767 -0.815368  1.0      39.333333
Saudi Arabia                0.976238 -1.022179  1.0      36.666667
Senegal                     1.343085 -1.077420  1.0      38.500000
Serbia                      1.066614 -0.916387  1.0      42.666667
Spain                       1.193911 -0.905726  1.0      67.000000
Switzerland                 1.024097 -1.300880  1.0      43.000000
Tunisia                     0.805353 -1.119304  1.0      38.666667
United States               0.767335 -1.435367  1.0      47.000000
Uruguay                     1.149932 -0.665750  1.0      41.000000
Wales                       0.867461 -1.093756  1.0      41.000000

## **Questions on IPL wala dataset**

ball by ball dataset - https://drive.google.com/file/d/1-kvv_9KCSAFWcrhS9WgTxSrURkRh6GNt/view?usp=share_link

###`Q-5:` Find batsman in below category-
* Highest score while chasing
* Best Strike rate while chasing and have faced 100+ balls


> Chasing mean team batting in second inning

In [181]:
ipl=pd.read_csv('/content/deliveries.csv')
temp=ipl[ipl['inning']==2]
df_temp=temp.groupby('batsman').agg({
    'batsman_runs':'sum',
    'ball':'count'
}).reset_index()
df_temp['Strike_rate']=(df_temp['batsman_runs']/df_temp['ball'])*100
df_temp=df_temp[df_temp['ball'] >= 100]
df_temp.sort_values(by='batsman_runs',ascending=False).iloc[0]

batsman         RV Uthappa
batsman_runs          2622
ball                  1981
Strike_rate     132.357395
Name: 349, dtype: object

In [ ]:
ipl.groupby('batsman')

###`Q-6` Most Successful bowler against any batsman. Find that pair of bowler and batsman.
> Most Successful in terms of dissmissal. A bowler who have dissmissed any batsman most no of times. If any two pairs have same no of dissmisal, consider runs conceded by bowler to that batsman. Those who have concede lesser runs is more successful.

In [134]:
ipl.groupby(['bowler','batsman']).agg({
    'player_dismissed':'count',
    'batsman_runs':'sum'}).sort_values(by=['player_dismissed','batsman_runs'],ascending=[False,True]).reset_index().iloc[0]

bowler               B Kumar
batsman             PA Patel
player_dismissed           7
batsman_runs              66
Name: 0, dtype: object

###`Q-7`: Most successful batting pair in IPL. Batting pair who have scored most runs playing together.

In [143]:
ipl.groupby(['batsman','non_striker'])['batsman_runs'].sum().reset_index().sort_values(by='batsman_runs',ascending=False).head(1)

       batsman non_striker  batsman_runs
1110  CH Gayle     V Kohli          1508

###`Q-8:` Make a dataframe for all batting pairs played together.
```
Batsman1 Batsman2 Runs Avg StrikeRate
```

> Just to ease this question you can count wide-balls for strike rate.

In [153]:
pair_df = ipl.groupby(['batsman','non_striker']).agg({
    'batsman_runs': 'sum',
    'ball': 'count'
}).reset_index()

pair_df.columns = ['Batsman1','Batsman2','Runs','BallsFaced']

pair_df['Avg'] = pair_df['Runs'] / pair_df['BallsFaced']
pair_df['StrikeRate'] = (pair_df['Runs'] / pair_df['BallsFaced']) * 100

pair_df = pair_df.sort_values(by='Runs', ascending=False)
pair_df

            Batsman1        Batsman2  Runs  BallsFaced       Avg  StrikeRate
1110        CH Gayle         V Kohli  1508        1006  1.499006  149.900596
270   AB de Villiers         V Kohli  1411         919  1.535365  153.536453
6023         V Kohli  AB de Villiers  1362         943  1.444327  144.432662
1337       DA Warner        S Dhawan  1354         935  1.448128  144.812834
6030         V Kohli        CH Gayle  1142         967  1.180972  118.097208
...              ...             ...   ...         ...       ...         ...
5925        TL Suman        RP Singh     0           1  0.000000    0.000000
576          AP Tare       SV Samson     0           1  0.000000    0.000000
2731         KK Nair    Ankit Sharma     0           2  0.000000    0.000000
2728         KK Nair        AM Nayar     0           3  0.000000    0.000000
3646        MS Bisla       YK Pathan     0           6  0.000000    0.000000

[6510 rows x 6 columns]